# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(null=True)),
                ('is_answered', models.BooleanField()),
                ('view_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
